### ISSUE TITLE
Excel Export Feature

### ISSUE THREAD

**Issue by vegsetup** [erykjj/jwlmanager#95] opened 2023-09-20 08:47 UTC
Morning Brothers,

I really enjoy using your JWLManager to clean up my JW information every few weeks.  I have also used it very successfully to help others clean out their bloated JW Library database.

However I also used https://github.com/AntonyCorbett/JWLMerge to export my study bible notes to Excel, both to share and as a backup.  The Excel export that Corbett made use of allowed very easy filtering of the exported information and in a simple format that could be shared. Unfortunately JWLMerge is now archived and no longer being developed, neither does it work with the current database schema of JW Library.

Would it be possible to adapt his Excel export code to work with your system to provide the same functionality?

Below is a sample of what the exported file from JWLMerge would look like.

[Copy of Export from JW Library.xlsx](https://github.com/erykjj/jwlmanager/files/12671012/Copy.of.Export.from.JW.Library.xlsx)

Thank you
Veg

**Comment by erykjj** [comment] 2023-09-20 13:45
Hi @vegsetup 

Thank you for your request.

I am currently implementing a CSV export feature for the upcoming v2.5.0 release. However, the CSV files aren't intended to be re-imported into JWLManager.

Please test this pre-release and let me know what you think. I'm very open to suggestions/observations ;-)

https://github.com/erykjj/jwlmanager/releases/tag/v2.5.0-RC2

**Comment by erykjj** [comment] 2023-09-20 13:54
Had to pull RC2. I had been testing on Linux and it worked fine. Tried on Windows10 and no go. Will release something later.

**Comment by erykjj** [comment] 2023-09-20 14:09
OK, try this one, please: https://github.com/erykjj/jwlmanager/releases/tag/v2.5.0-RC3

**Comment by vegsetup** [comment] 2023-09-20 14:34
Thank you very much, will test tonight and keep you posted.

**Comment by vegsetup** [comment] 2023-09-20 15:31
I am not finding a CSV export option in the Stand-alone JWLManager_v2.5.0-RC3.exe.

Going to try the ZIP file now and see if I can see it there.

**Comment by vegsetup** [comment] 2023-09-20 15:38
Okay, same experience on the ZIP file.

I copy my jwlibrary file in JWLManager

Select my Study Bible, leave it on Notes and Title

Click Export, click Yes to proceed

Try and save as type CSV, only option is TXT

I exported as TXT and it is in the same format as the older version, not a CSV.

I may be doing something wrong or not looking in the right place.  Please let me know.

**Comment by vegsetup** [comment] 2023-09-20 16:20
Okay, found it.

By clicking on the VIEW button you presented with the option of CSV and TXT and then whatever you select gives the option to save as a CSV and TXt.

Have a look now at CSV output

**Comment by vegsetup** [comment] 2023-09-20 18:11
Evening my Brother,

First of all, brilliant job so far!!!!! It is really looking great and I am sure everyone is going to appreciate the extra features. I mostly focused on the study bible. For the most part you could not ask for more, column breakdown gives you a lot of flexibility, filtering and is a superb way of backing up your notes or sharing information.  The TAGS and how you have exported that in the CSV format is nicely formatted.  Just some suggestions:

The REFERENCE column is not always returning the bible book name and chapter. 

This is only affecting BOOK 6, 16, 17, 19, 20, 40, 43, 44.

This is not consistent however, sometimes these books do return the bible book name and chapter in the REFERENCE column.  I could not find any trigger or reason why this is only affecting certain chapters in these books. It may be different for others database but that is what is happening with my database..

All the other BOOK's are reflecting the bible book name and chapters.

----------------

Just a suggestion, the REFERENCE column does not need to include the chapter as this is also listed in the CHAPTER column

Also, suggest mapping the REFERENCE column after column BOOK and rename as NAME (or something like that) then it follows in normal bible book format Bible Book, Chapter, Verse

Also suggest renaming the column BLOCK to VERSE

---------------


My instinct was to use the EXPORT feature in JWLManager to get the information and that confused me when I could not find CSV.  Playing around I found how you implment this feature in the VIEW feature.  I am sure if this is explained in the Help file it would help.

----------------

**Content**
Most of these observations below related to character set.  Seems it might be exported in the UTF8 character set.  I tried importing it into Excel with a few different character sets and it helped a little but did not remove all incorrect characters.  Not sure if you could list or indicate possibly what character set you used for the export:

 In JW Library notes, hard returns (pressing enter to create a space) shows up in the CSV notes as "\n\n". This could easily be removed in Excel with find and replace

In JW Library notes, soft returns (holding shift and enter) shows up in the CSV notes as " \n". This could easily be removed in Excel with find and replace

In JW Library, anything with an apostrophe, for instance "Jehovah's" comes up as follows in the CSV notes: Jehovahâ€™s

In JW Library, when you copy past something like this in the notes: ....of great help.—Prov. 16:21, 23. It shows up in the CSV notes as follows: ....of great help.â€‹â€”Prov. 16:21, 23

In JW Library, open and close quotation marks eg. "......." show up like this in the CSV notes: e: â€œFor everything there is an appointed time, . . . a time to keep quiet and a time to speak.â€ (Ecclesiastes 3:1, 7)

In JW Library, anything like this To·biʹah’s comes up with this in the CSV ToÂ·biÊ¹ahâ€™s

**Comment by glenmwright** [comment] 2023-09-20 19:20
I have found that if you view the csv in a text editor it displays in the correct character set without the "â€‹â€”" characters. In Excel if I open the CSV file, I get the different characters. However, if I open a blank Excel spreadsheet and then Get Data and import the CSV, the characters are displayed correctly using UTF-8. However, the downside is that it seems to mess up on fields without double quotes as text qualifiers. I notice sometimes the Title and Content are surrounded by "" and sometimes not.

**Comment by erykjj** [comment] 2023-09-20 21:07
Wow, you guys have been busy :-) Thank you for all that feedback (from both). I'll try to address these points and lets see if we can smooth it out a bit ;-)

**Comment by erykjj** [comment] 2023-09-20 21:12
![2023-09-20_17-09-47](https://github.com/erykjj/jwlmanager/assets/107011362/22229cca-515f-485b-b7fd-f53eaa3539dd)
I open the CSV file (in Linux) with Open With... LibreOffice Calc and it automatically selects the UTF-8 encoding. All I need to do is to click OK and the sheet opens. Do you not have the same option?

And, yes, all the files are Unicode (UTF-8) formatted.

**Comment by erykjj** [comment] 2023-09-20 21:13
The CSV and TXT buttons are in the Data Viewer window, as they are _not_ the official export/import functions. They are more limited (for now) and for special-use cases.

**Comment by erykjj** [comment] 2023-09-20 21:20
> The REFERENCE column is not always returning the bible book name and chapter.

Good catch. Found a bug. Will be fixed.

**Comment by erykjj** [comment] 2023-09-20 21:25
> Also suggest renaming the column BLOCK to VERSE

This varies between Bibles (verse) and other publications (paragraph block). It is called BlockIdentifier in the SQLite db, so I will leave it as such.

**Comment by erykjj** [comment] 2023-09-20 21:29
> Just a suggestion, the REFERENCE column does not need to include the chapter as this is also listed in the CHAPTER column
> 
> Also, suggest mapping the REFERENCE column after column BOOK and rename as NAME (or something like that) then it follows in normal bible book format Bible Book, Chapter, Verse

The reference column contains the subheading or title of the article where the BlockIdentifier is located. In case of notes associated with the Bible, it will include the Book name and chapter only. I've added the verse for completeness (though Jude 21 will show up as Jude 1:21. It's too complicated to filter worry about which books only have one chapter, etc. The column is there just for... reference :-) Everything can be sorted/filtered by the other columns.

**Comment by erykjj** [comment] 2023-09-20 21:32
> My instinct was to use the EXPORT feature in JWLManager to get the information and that confused me when I could not find CSV. Playing around I found how you implment this feature in the VIEW feature. I am sure if this is explained in the Help file it would help.

HELP file updated. Thanks.

**Comment by erykjj** [comment] 2023-09-20 21:38
> In JW Library notes, hard returns (pressing enter to create a space) shows up in the CSV notes as "\n\n". This could easily be removed in Excel with find and replace
> 
> In JW Library notes, soft returns (holding shift and enter) shows up in the CSV notes as " \n". This could easily be removed in Excel with find and replace

\n represents a newline character. Since CSV allows only one line per entry, some character has to be used to indicate line-breaks. That is why the 'official' export/import text file format is delimited by a header (all those ==={} attribute fields): it allows for searching, editing, cutting/pasting, etc.

**Comment by erykjj** [comment] 2023-09-20 21:39
Please tell me if the UTF-8 formatting is adding unnecessary complexity to opening the files on Windows. If so, we may have to rethink it. But I would prefer to keep it, as it is... 'universal'.

**Comment by erykjj** [comment] 2023-09-20 23:08
Also, since we are at this point, I'd appreciate some ideas about the export/import format. Is it too complicated with all those {ATTRIBUTE=} fields? Any suggestions about a text-file format that easily be read/edited and still contain all the meta-information about thousands of notes??

**Comment by erykjj** [comment] 2023-09-21 00:03
> > The REFERENCE column is not always returning the bible book name and chapter.
> 
> Good catch. Found a bug. Will be fixed.

Please test this: https://github.com/erykjj/jwlmanager/releases/tag/v2.5.0-RC4

**Comment by vegsetup** [comment] 2023-09-21 04:05
> Please tell me if the UTF-8 formatting is adding unnecessary complexity to opening the files on Windows. If so, we may have to rethink it. But I would prefer to keep it, as it is... 'universal'.

Morning, makes perfect sense now that it is a universal standard for line breaks.  That can also be rectified by the person using excel/libre fine and replace.

**Comment by vegsetup** [comment] 2023-09-21 04:07
> I have found that if you view the csv in a text editor it displays in the correct character set without the "â€‹â€”" characters. In Excel if I open the CSV file, I get the different characters. However, if I open a blank Excel spreadsheet and then Get Data and import the CSV, the characters are displayed correctly using UTF-8. However, the downside is that it seems to mess up on fields without double quotes as text qualifiers. I notice sometimes the Title and Content are surrounded by "" and sometimes not.

Thanks Glen, that helped a lot.  Going this route eradicated all the special characters.  Also tested Libre and works fine in Libre as well so that resolves those issues.  Might be good to mention in the help to use UTF-8 character set if neccessary to clean up the exported data.

**Comment by vegsetup** [comment] 2023-09-21 04:08
> Please tell me if the UTF-8 formatting is adding unnecessary complexity to opening the files on Windows. If so, we may have to rethink it. But I would prefer to keep it, as it is... 'universal'.

I don't think so.  It works brilliantly for almost 100% of the data export.  Agree best to keep as universal.

**Comment by vegsetup** [comment] 2023-09-21 04:25
> > > The REFERENCE column is not always returning the bible book name and chapter.
> > 
> > 
> > Good catch. Found a bug. Will be fixed.
> 
> Please test this: https://github.com/erykjj/jwlmanager/releases/tag/v2.5.0-RC4

Brilliant!!!!!!

REFERENCE field is now fully populated withe the chapter and verse.  Excellent and then they can use the preceding columns to filter book and chapter if neccessary.  Very nice, clear and understandable.

RC4 also correctly shows the link now which works well.

All special characters other than the standard newline character resolved in RC4.

**Comment by vegsetup** [comment] 2023-09-21 04:36
> > > The REFERENCE column is not always returning the bible book name and chapter.
> > 
> > 
> > Good catch. Found a bug. Will be fixed.
> 
> Please test this: https://github.com/erykjj/jwlmanager/releases/tag/v2.5.0-RC4

I checked this on a few publications. 

On the SFL all REFERENCE fields correctly populated.

On the LFF however there are some REFERENCE fields that are coming up blank. The LINK column in the LLF is also all blank. It seems that the REFERENCE field is blank from start of Aug 2023. Before then it was working fine.

**Comment by vegsetup** [comment] 2023-09-21 04:52
> Also, since we are at this point, I'd appreciate some ideas about the export/import format. Is it too complicated with all those {ATTRIBUTE=} fields? Any suggestions about a text-file format that easily be read/edited and still contain all the meta-information about thousands of notes??

Anthony did something similar in https://github.com/AntonyCorbett/JWLMerge/wiki. The way he showed the attributes may be a bit simpler but it is still a txt file with attributes.

Maybe now that we have the CSV the export/import feature as is works is fine.  The CSV gives those a little more technically challenge an option to export, view, backup, share and then for the more advanced users the TXT file will work for editing and reimporting.

**Comment by erykjj** [comment] 2023-09-21 13:55
> Maybe now that we have the CSV the export/import feature as is works is fine. The CSV gives those a little more technically challenge an option to export, view, backup, share and then for the more advanced users the TXT file will work for editing and reimporting.

The thing is, though, that you cannot re-import from the CSV file through JWLManager - it's a one-way export-only operation.

**Comment by erykjj** [comment] 2023-09-21 13:55
> On the LFF however there are some REFERENCE fields that are coming up blank. The LINK column in the LLF is also all blank. It seems that the REFERENCE field is blank from start of Aug 2023. Before then it was working fine.

I will have to look into this. Thank you for reporting!

**Comment by erykjj** [comment] 2023-09-21 14:37
> > On the LFF however there are some REFERENCE fields that are coming up blank. The LINK column in the LLF is also all blank. It seems that the REFERENCE field is blank from start of Aug 2023. Before then it was working fine.
> 
> I will have to look into this. Thank you for reporting!

Hm, I tested with some notes created today in lff-S and they all showed up correctly, both in the reference and link fields...

Any way you can share your db? Just delete all the other notes (leaving only the "problematic" ones, and MASK the remaining ones, then attach the .jwlibrary backup (you may have to add a .zip extension)

**Comment by vegsetup** [comment] 2023-09-21 16:39
> > > On the LFF however there are some REFERENCE fields that are coming up blank. The LINK column in the LLF is also all blank. It seems that the REFERENCE field is blank from start of Aug 2023. Before then it was working fine.
> > 
> > 
> > I will have to look into this. Thank you for reporting!
> 
> Hm, I tested with some notes created today in lff-S and they all showed up correctly, both in the reference and link fields...
> 
> Any way you can share your db? Just delete all the other notes (leaving only the "problematic" ones, and MASK the remaining ones, then attach the .jwlibrary backup (you may have to add a .zip extension)

[MODIFIED_2023-09-21.zip](https://github.com/erykjj/jwlmanager/files/12688949/MODIFIED_2023-09-21.zip)

Here is LFF masked, all other information deleted.  See if it comes up the same on your side.

**Comment by erykjj** [comment] 2023-09-21 20:29
OK. Found another bug, which also got squashed. Now the links should be generated correctly. I will release another RC shortly.

As to the blank reference column, the reason is that it is blank in the db:
![2023-09-21_16-22-45](https://github.com/erykjj/jwlmanager/assets/107011362/99b18343-a2c0-4f8f-86c9-d1c2408e3817)

The reason for this (most likely) is that you exported those notes using JWLManager and later imported them. The current releases did not export the Title field from the Location table, and so that info would be lost. I have also corrected that in this upcoming release. Your help is, indeed, invaluable. Thank you!

**Comment by erykjj** [comment] 2023-09-21 20:47
Please test your db with RC5. Links should show. The empty reference field will have to remain empty; it's won't affect operation in any way.

https://github.com/erykjj/jwlmanager/releases/tag/v2.5.0-RC5

**Comment by glenmwright** [comment] 2023-09-22 13:15
The addition of the links is very cool. I am getting some errors in the CSV. Sometimes TITLE and CONTENT are wrapped in double quotes and other times they are not.  Also, it seems there are cases when the end of line characters are not replaced with \n

![image](https://github.com/erykjj/jwlmanager/assets/85457329/3b6cc3bb-9e2a-4da4-9725-ec2f3fd278e2)

**Comment by vegsetup** [comment] 2023-09-22 17:26
Evening Brothers,

The links are working perfectly.

I am still struggling with the LFF though.  I created two new records and the REFERENCE column is still blank for those two  new records.  You will see that in the Excel attached, the records were created today the 22nd September. The behavior only started beginning of August??? The REFERENCE column is the chapter title.

The other thing I noticed in the LFF csv and Excel, JWLManager is not exporting the CHAPTER number in it's column, it is only exporting the BLOCK number (verse).  So if you don't have the chapter title that appears in the REFERENCE column or the chapter number in the CHAPTER column, you don't actually know which chapter the notes and title are in.  That make sense?

I have also included the database and excel, neither are masked, no worries.
[LFF Notes.xlsx](https://github.com/erykjj/jwlmanager/files/12703121/LFF.Notes.xlsx)
[LFF Export.zip](https://github.com/erykjj/jwlmanager/files/12703126/LFF.Export.zip)
[LFF Notes.csv](https://github.com/erykjj/jwlmanager/files/12703128/LFF.Notes.csv)

Thank you

**Comment by erykjj** [comment] 2023-09-23 00:41
> The addition of the links is very cool. I am getting some errors in the CSV. Sometimes TITLE and CONTENT are wrapped in double quotes and other times they are not. Also, it seems there are cases when the end of line characters are not replaced with \n
> 
> ![image](https://user-images.githubusercontent.com/85457329/269946670-3b6cc3bb-9e2a-4da4-9725-ec2f3fd278e2.png)

@glenmwright , could you send me the .jwlibrary archive with those problematic notes for further investigation? You can email to me directly.

**Comment by erykjj** [comment] 2023-09-23 00:56
> The other thing I noticed in the LFF csv and Excel, JWLManager is not exporting the CHAPTER number in it's column, it is only exporting the BLOCK number (verse). So if you don't have the chapter title that appears in the REFERENCE column or the chapter number in the CHAPTER column, you don't actually know which chapter the notes and title are in. That make sense?

This is correct. Chapter is only in the case of Bible notes. All other publications use a DocumentId (along with IssueTagNumber for periodical pubs) to identify each article/chapter/document. That, along with the block is enough to locate the paragraph.

But you did catch another oversight on my part: I didn't include the DocumentId in the CSV. I will add it now.

**Comment by erykjj** [comment] 2023-09-23 01:03
> I am still struggling with the LFF though. I created two new records and the REFERENCE column is still blank for those two new records. You will see that in the Excel attached, the records were created today the 22nd September. The behavior only started beginning of August??? The REFERENCE column is the chapter title.

This is strange. I just created a note in lff-S, and the Location.Title field was correctly populated by the app. In your case, the fields are blank.

Is your JW Library app up-to-date? What version and operating system? Is the lff up-to-date?

**Comment by vegsetup** [comment] 2023-09-23 04:32
Morning, 

Just another small suggestion. If you have have a database open in JWLManager and you then open the Data View and look at either the CSV or TXT.  When you click FILE-New to remove the current database, you should also close the Data View window.  Otherwise the database is gone but the Data View window still has a view of the csv or txt.

**Comment by vegsetup** [comment] 2023-09-23 04:51
> > I am still struggling with the LFF though. I created two new records and the REFERENCE column is still blank for those two new records. You will see that in the Excel attached, the records were created today the 22nd September. The behavior only started beginning of August??? The REFERENCE column is the chapter title.
> 
> This is strange. I just created a note in lff-S, and the Location.Title field was correctly populated by the app. In your case, the fields are blank.
> 
> Is your JW Library app up-to-date? What version and operating system? Is the lff up-to-date?

Okay, tested with both my laptops:

Work Machine:
Windows ver 11 22H2 22621.2283
JW Library ver 14.0.163 (316609)

Personnel Machine:
Windows ver 11 22H2 22621.2283
JW Library ver 14.1.34 (324551)

On my work machine I did the following:
Deleted lff and redownloaded
Deleted database and started with fresh database and new lff
Same result, no information in the REFERENCE column

On my personnel machine tried the same steps:
In addition, tried the LFFi (Introductory Brochure)
Also no information in the REFERENCE column.

Here are the files for you too test your side:

[New Database redownloaded book - UserdataBackup_2023-09-23_ZA5CD1514LY5.zip](https://github.com/erykjj/jwlmanager/files/12705608/New.Database.redownloaded.book.-.UserdataBackup_2023-09-23_ZA5CD1514LY5.zip)
[lffi same database  same problem.xlsx](https://github.com/erykjj/jwlmanager/files/12705609/lffi.same.database.same.problem.xlsx)
[lff new database same problem.xlsx](https://github.com/erykjj/jwlmanager/files/12705610/lff.new.database.same.problem.xlsx)
[lffi_E.zip](https://github.com/erykjj/jwlmanager/files/12705614/lffi_E.zip)

You mention you testing with lff-s?  What language is that?  I have attached the lffi-e (Life Forever Introductory English) which is what I was testing with.

**Comment by erykjj** [comment] 2023-09-23 11:37
> Just another small suggestion. If you have have a database open in JWLManager and you then open the Data View and look at either the CSV or TXT. When you click FILE-New to remove the current database, you should also close the Data View window. Otherwise the database is gone but the Data View window still has a view of the csv or txt.

The jury is out on this one :-) But I'll definitely take not of your suggestion. Thank you.

**Comment by erykjj** [comment] 2023-09-23 12:05
![2023-09-23_07-49-17](https://github.com/erykjj/jwlmanager/assets/107011362/dcd93279-26a8-40f6-81be-462fc744f436)
![2023-09-23_07-57-45](https://github.com/erykjj/jwlmanager/assets/107011362/7b50c258-973e-42db-b3c2-09718b5f498f)

So, I have tested and observe a similar behavior. It appears that when a note is added to a _heading_ (question or title), the Title field in the Location column is blank. Any subsequent notes added at that location (DocumentId) will reference that same db entry and show up blank. Notice that notes created within a paragraph _do_ show. Please test with a blank archive: save a blank archive in JWLManager and restore that in your JW Library, then add some notes.

If confirmed, this could be a bug in JW Library. When did v14 come out?

**Comment by vegsetup** [comment] 2023-09-23 13:40
> ![2023-09-23_07-49-17](https://user-images.githubusercontent.com/107011362/270105553-dcd93279-26a8-40f6-81be-462fc744f436.png) ![2023-09-23_07-57-45](https://user-images.githubusercontent.com/107011362/270105555-7b50c258-973e-42db-b3c2-09718b5f498f.png)
> 
> So, I have tested and observe a similar behavior. It appears that when a note is added to a _heading_ (question or title), the Title field in the Location column is blank. Any subsequent notes added at that location (DocumentId) will reference that same db entry and show up blank. Notice that notes created within a paragraph _do_ show. Please test with a blank archive: save a blank archive in JWLManager and restore that in your JW Library, then add some notes.
> 
> If confirmed, this could be a bug in JW Library. When did v14 come out?

Okay, Saved a new database from JWLManager
[Blank database from JWLManager.zip](https://github.com/erykjj/jwlmanager/files/12706532/Blank.database.from.JWLManager.zip)

Opened in JW Library, made changes and saved back to database
[Changes made to blank database from JWLManager.zip](https://github.com/erykjj/jwlmanager/files/12706534/Changes.made.to.blank.database.from.JWLManager.zip)

Updated database copied back to JWLManager and exported to a CSV
[Changes made to new database from JWL.csv](https://github.com/erykjj/jwlmanager/files/12706537/Changes.made.to.new.database.from.JWL.csv)
[Changes made to blank database from JWLManager.xlsx](https://github.com/erykjj/jwlmanager/files/12706540/Changes.made.to.blank.database.from.JWLManager.xlsx)

Experience the same. REFERENCE which I believe is your TITLE in the picture above remains blank. Uploads included to see if you see the same.

I am in South Africa Bethel and it all the JW Library versions we running at the branch are on ver 14.  I am also on a beta test group for JW Library so am on a slightly later version.

I then also tried with an earlier backup of mine from July. All the information was there in the REFERENCE column except for the new entries I put in the old database.  All of that points to something changing at the beginning of August. I noted that the latest version on the website is also ver 14 https://www.jw.org/en/online-help/jw-library/windows/manually-install-windows/

What version you running?

**Comment by erykjj** [comment] 2023-09-23 14:19
Hm, so even your "regular text" notes don't generate the Location.Title field:
![2023-09-23_09-59-34](https://github.com/erykjj/jwlmanager/assets/107011362/6a2947c3-5b88-4fae-913c-f2f60b8e944f)

I am testing on a Windows 10 Virtualbox machine, using the Microsoft Store version of JW Library, which did generate those fields for me in the "regular" paragraph notes (as above) - though I tested again with another publication, and it's on and off... **In any case, I don't see this as a bug with JWLManager, as I'm looking at the actual db in the .jwlibrary backups**, not the CSV files. You may want to report it for further testing. It may be related to whether the note is highlighted or not.

**Comment by erykjj** [comment] 2023-09-23 15:52
I released another test version: v3.0.0-beta1, since I'm planning to rethink/redo the {ATTRIBUTE=} note headers:

https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-beta1

Please test the reported \n and double-quote issues.

**Comment by erykjj** [comment] 2023-09-24 00:20
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-beta2

Now with Excel export (from within Data Viewer) :-)

**Comment by vegsetup** [comment] 2023-09-24 04:44
> https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-beta2
> 
> Now with Excel export (from within Data Viewer) :-)

Very nice!!! Also noticed that the data viewer actually shows the color of the notes as well.  Might have been there before but just noticed it now, clever detail.

Something is different with beta2 as the XLS is now showing the DOCUMENTID which it did not before but still not the actual chapter name.

![2023-09-24 06_13_25-Notes xlsx - Excel](https://github.com/erykjj/jwlmanager/assets/145546142/5da2f4d3-46f5-45e8-a529-7f2a3f130a00)

I have attached the files here for you review:

[Notes.xlsx](https://github.com/erykjj/jwlmanager/files/12707773/Notes.xlsx)

[Changes made to blank database from JWLManager (2).zip](https://github.com/erykjj/jwlmanager/files/12707772/Changes.made.to.blank.database.from.JWLManager.2.zip)

Also seems the double quotes in the study bible fixed but Glen can confirm.  I may be out of comms for a week but will catch up when I am back. Thank you so much for all the work on this, very exciting and helpful.

**Comment by erykjj** [comment] 2023-09-24 12:45
> the XLS is now showing the DOCUMENTID which it did not before but still not the actual chapter name

Yes, thanks to you I noticed that DocumentId was missing and added it.

As I mentioned before, the chapter only applies to Bible notes. Other publications don't use that field. They locate by the DocumentId and Block fields, and the reference column (Location.Title) is what should show the chapter title as generated by the app (usually including the chapter number, as it does in lff).

**Comment by erykjj** [comment] 2023-10-01 00:56
Moving forward... export/import to/from Excel is implemented now via the buttons on the main interface (no longer in the  Data Viewer window) - just change the extension to .xlsx when choosing filename for your export. Should work with Notes and Annotations.

**FOR TESTING ONLY**
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-beta4

**Comment by erykjj** [comment] 2023-10-03 21:03
@vegsetup please test as thouroughly as you can. Thank you!
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-RC

**Comment by erykjj** [comment] 2023-10-03 23:20
Already found and squashed a couple of bugs since the last release :-)

**Comment by erykjj** [comment] 2023-10-04 19:48
This will be the final pre-release:
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-RC2

**Comment by vegsetup** [comment] 2023-10-04 20:08
Hi Eryk, just back. Wil start testing.

**Comment by vegsetup** [comment] 2023-10-05 04:08
Morning Eryk,

In RC2, with the bible notes in the study bible, the reference or HEADING column is now only showing the book and chapter, not the verse for completeness.  Have attached my Excel so you can see.

Also, with the bible notes in the study bible, I could not find a pattern but some of the references/HEADINGS are now showing up while others are not.  This again has only started since August. I sorted by date created and date modified and again in both instances some appear and others nots.  Will see in the Excel as well. As an example, if you filter out BOOK 16 in the EXCEL you will see some of the references/HEADINGS are there but others not. Interestingly nothing is there for BOOK 17 which is Esther.

[JWL_Notes_2023-10-05.xlsx](https://github.com/erykjj/jwlmanager/files/12812132/JWL_Notes_2023-10-05.xlsx)

It seems import from Excel is not working.  When I press on IMPORT it wants it in UTF-8 format, does not give you the option to import in XLSX format.  When you proceed you can choose which format you want to import but when you choose XLSX it pops up with the following error:

JWLManager v3.0.0-RC2
Windows-10-10.0.22621-SP0

Traceback (most recent call last):
  File "pandas\compat\_optional.py", line 132, in import_optional_dependency
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JWLManager.py", line 1646, in __init__
  File "pandas\io\excel\_base.py", line 504, in read_excel
  File "pandas\io\excel\_base.py", line 1580, in __init__
  File "pandas\io\excel\_openpyxl.py", line 552, in __init__
  File "pandas\compat\_optional.py", line 135, in import_optional_dependency
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

Here is a copy of the excel I was trying to import and you will notice the one change I made to line 5 on Title and Note

[JWL_Notes_2023-10-05.xlsx](https://github.com/erykjj/jwlmanager/files/12812170/JWL_Notes_2023-10-05.xlsx)

I have not done any testing yet on publications.

**Comment by erykjj** [comment] 2023-10-05 14:06
Welcome back and thanks for the report!!! It was a missing dependency (required for reading the Excel file). I've added it into the build process now. I've also removed the alert about UTF-8 formatting as it doesn't apply to MS Excel files. Please test again with this (last :-)) pre-release:
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-RC3

As to the empty HEADINGs, I have a pretty good idea what's up with that, and just need to make a decision as to how to proceed. So I'll explain later and get your input then ;-)

**Comment by erykjj** [comment] 2023-10-05 14:11
I just noticed that the zipped Windows build almost trippled in size!!! Something is not right there - I just added a small library/module. I'll have to look into that now ;-\

**Comment by erykjj** [comment] 2023-10-05 14:30
> I just noticed that the zipped Windows build almost trippled in size!!! Something is not right there - I just added a small library/module. I'll have to look into that now ;-\

Fixed: https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-RC4

**Comment by erykjj** [comment] 2023-10-05 16:03
So, about the HEADINGs, here is your export, with book 17 (Esther) showing blank in the HEADING column:
![2023-10-05_11-46-06](https://github.com/erykjj/jwlmanager/assets/107011362/82a619c8-49bc-4aaf-b910-845abfb939bd)

In the Data Viewer, I generate the reference (including the verse), but it is based on the currently-selected language (not the language of the Bible edition):
![2023-10-05_11-49-13](https://github.com/erykjj/jwlmanager/assets/107011362/3f8d65f1-c139-41b4-93fb-2fa3e3b30306)

The JW Library app, generates this reference (Book and Chapter only), based on the language of the Bible used - even though in the archive it is blank:
![2023-10-05_11-50-43](https://github.com/erykjj/jwlmanager/assets/107011362/fe7d9821-71a0-49cc-bf76-99a143700654)

What it comes down to is that the information in that field is generated/updated in  on-the-spot the JW Library app. It also appears that (as of v14 of the JW Library app), that field (in the database) isn't even used.

I will keep the Data Viewer feature, but I'm thinking of not including the HEADING field in the export/import process. What do you think? **How useful is it to have it in the Excel?** One can sort by BK, CH and VS. Does one need to see "Esther 9" in there? Would "Esther 9:10" be even more useful/practical?

Please think about this and give me your input ;-)

**Comment by vegsetup** [comment] 2023-10-05 17:57
Okay, tested RC4 with the study bible.

Export and Import work well now with no errors or UTF-8 message popping up.  There is one thing I noticed with the import.  I edited the one line in the excel spreadsheet, when I imported the Excel spreadsheet into JWLManager I noticed that the note count increased by two.  It seems that the JWLManager added an extra note instead of editing it. This was also evident in JW Library, the editing I did in Excel did not edit the note, it left the old note and it added the editing as a separate note on the same scripture.  That may be by design but thought it worth while mentioning.

On your explanation above about the HEADING, I noticed something similar.  In the screen shot below, the first two records where created days apart and are from the same book. When the DataViewer has the Book | Chapter then it shows in the HEADING column on the Excel sheet.  When the DataViewer has the Book | Chapter | Verse it comes up as blank in the HEADING column. Somehow it seems the records that have the Book | Chapter | Verse mostly always have TAGS on them....????

![2023-10-05 19_07_56-Data Viewer_ 46 Notes](https://github.com/erykjj/jwlmanager/assets/145546142/34462a85-4671-4c95-9eb2-21f07c7adfde)

On your question of how useful it is to have the BOOK name in Excel, from my vantage point it is very useful and important.  The best of us is never going to know which bible book is "40" or "17". The actual name helps to clarify that very quickly. Having something like "Esther 9:10" in the Excel sheet is very useful and practical?

**Comment by erykjj** [comment] 2023-10-05 19:26
> There is one thing I noticed with the import. I edited the one line in the excel spreadsheet, when I imported the Excel spreadsheet into JWLManager I noticed that the note count increased by two. It seems that the JWLManager added an extra note instead of editing it. This was also evident in JW Library, the editing I did in Excel did not edit the note, it left the old note and it added the editing as a separate note on the same scripture. That may be by design but thought it worth while mentioning.

Very good observations. By design: if the TITLE changes, another note is added, even if NOTE is exactly the same; if the TITLE is unchanged, the note is overwritten by the last one to be imported. Please confirm this is what is happening.

**Comment by vegsetup** [comment] 2023-10-05 19:27
On the Enjoy Life and Watchtowers

The Export and import to XLS work well.  

This may be a repeat of what was said before but just in case:

In the Enjoy Life, the CHAPTER name is working in the HEADING column for CHAP 52 but then stops in CHAP 53
In the Watchtower, the ARTICLE name is working in the HEADING column for the May 2023 Study Article 23 but then stops in the May 2023 Study Article 24.

**Comment by erykjj** [comment] 2023-10-05 19:28
> When the DataViewer has the Book | Chapter then it shows in the HEADING column on the Excel sheet. When the DataViewer has the Book | Chapter | Verse it comes up as blank in the HEADING column.

The Data Viewer adds the "Book Chapter:Verse" only if the field was empty. I can adjust that for all fields.

**Comment by erykjj** [comment] 2023-10-05 19:29
> On the Enjoy Life and Watchtowers
> 
> The Export and import to XLS work well.
> 
> This may be a repeat of what was said before but just in case:
> 
> In the Enjoy Life, the CHAPTER name is working in the HEADING column for CHAP 52 but then stops in CHAP 53 In the Watchtower, the ARTICLE name is working in the HEADING column for the May 2023 Study Article 23 but then stops in the May 2023 Study Article 24.

That's why I'm pretty sure it's not related to my app but the way JW Library writes to the database in the archive. Bug???

**Comment by vegsetup** [comment] 2023-10-05 19:36
> Very good observations. By design: if the TITLE changes, another note is added, even if NOTE is exactly the same; if the TITLE is unchanged, the note is overwritten by the last one to be imported. Please confirm this is what is happening.

Excellent, confirmed this is how it is working. Thank you for the explanation.

**Comment by erykjj** [comment] 2023-10-05 20:29
OK, final one (I hope :-)
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0-RC5
Please tell me if this behaves as expected/desired. Thank you for all your testing, @vegsetup !!

**Comment by vegsetup** [comment] 2023-10-06 05:03
Morning Eryk,,

It may be a bug as you say but the BETA testers have not mentioned any problems.  Will keep my eyes and ears open.  

For myself personally, having something like "Esther 9:10" in the Excel sheet for the study bible is important as it provides a easy way to isolate the scripture the title and note is referring too.  

In the Enjoy Life publication and even the Watchtower it is less important as you able to work out the chapter of each record by looking at the DOCUMENT column of the Enjoy Life and the ISSUE column of the Watchtower.   

Enjoy your day.

**Comment by erykjj** [comment] 2023-10-06 11:41
How about something like 17009010 (BBCCCVVV) for the scripture references? Would that help? That's already in the link.

**Comment by vegsetup** [comment] 2023-10-06 19:37
Hi Eryk,

That is an option, one would just have to find out which book is 17 to know
where your are in the Bible. In the list editing you could always do a
search and replace in the excel sheet or add another column to add the
actual book name.

Not as nice as the actual full scripture listed Esther 9:10 but maybe that
is all that is possible with the current database structure.

Thanks Eryk, hope the weekend goes well.

**Comment by erykjj** [comment] 2023-10-08 01:12
https://github.com/erykjj/jwlmanager/releases/tag/v3.0.0

**Closed by erykjj** 2023-10-08 01:12 UTC
Labels: enhancement
